namespace: elchico2007
name: chatgpt
version: 1.0.0
readme: README.md
authors:
- Luis Valle <levalle232@gmail.com>
description: Collection utilizing openAI's API to make queries via Ansible easier
license_file: LICENSE
tags: ['ai', 'openai', 'chatgpt', 'gpt3']
repository: https://github.com/elchico2007/elchico2007.chatgpt
issues: https://github.com/elchico2007/elchico2007.chatgpt/issues
